In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

In [ ]:
df=pd.read_csv("Datasets/house_price.csv")

In [3]:
df.head()

Unnamed: 0      Location  BHK  Furnishing  Sq.ft  Old(years)  Floor  Price
0          37    Whitefield    3           1   3000           1      3  28000
1          43  Bommanahalli    3           1   1650          10      0  18000
2          12    Whitefield    2           0   1000           5      3  16400
3           8    Whitefield    3           0   1600           1      9  27000
4           9    Whitefield    2           1   1200           5      1  20000

In [4]:
df.count()

Unnamed: 0    1000
Location      1000
BHK           1000
Furnishing    1000
Sq.ft         1000
Old(years)    1000
Floor         1000
Price         1000
dtype: int64

In [5]:
df.Floor.unique()

array([ 3,  0,  9,  1,  8, 10,  7, 13,  2, 12, 11,  4])

In [6]:
df.shape

(1000, 8)

In [7]:
df.dtypes

Unnamed: 0     int64
Location      object
BHK            int64
Furnishing     int64
Sq.ft          int64
Old(years)     int64
Floor          int64
Price          int64
dtype: object

In [8]:
df.isna().sum()

Unnamed: 0    0
Location      0
BHK           0
Furnishing    0
Sq.ft         0
Old(years)    0
Floor         0
Price         0
dtype: int64

In [9]:
df.max()

Unnamed: 0            49
Location      Whitefield
BHK                    3
Furnishing             1
Sq.ft               3155
Old(years)            10
Floor                 13
Price              45000
dtype: object

In [10]:
df.min()

Unnamed: 0               0
Location      Bommanahalli
BHK                      2
Furnishing               0
Sq.ft                  767
Old(years)               1
Floor                    0
Price                11000
dtype: object

In [11]:
#df =df.iloc[:,1:]
df = df.drop(['Unnamed: 0'], axis=1)

In [12]:
df.head()

Location  BHK  Furnishing  Sq.ft  Old(years)  Floor  Price
0    Whitefield    3           1   3000           1      3  28000
1  Bommanahalli    3           1   1650          10      0  18000
2    Whitefield    2           0   1000           5      3  16400
3    Whitefield    3           0   1600           1      9  27000
4    Whitefield    2           1   1200           5      1  20000

In [13]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.metrics import accuracy_score

In [14]:
label_enc = LabelEncoder()

In [15]:
#df.iloc[:,0] = label_enc.fit_transform(df.iloc[:,0])
#Data encoding
df['Location'] = label_enc.fit_transform(df['Location'])
df.head()

Location  BHK  Furnishing  Sq.ft  Old(years)  Floor  Price
0         1    3           1   3000           1      3  28000
1         0    3           1   1650          10      0  18000
2         1    2           0   1000           5      3  16400
3         1    3           0   1600           1      9  27000
4         1    2           1   1200           5      1  20000

In [16]:
#df = df.drop(['Unnamed: 0'], axis = 1)

In [17]:
#Data Preperation 
X = df.drop('Price', axis=1)
y = df['Price']

In [18]:
X.head()

Location  BHK  Furnishing  Sq.ft  Old(years)  Floor
0         1    3           1   3000           1      3
1         0    3           1   1650          10      0
2         1    2           0   1000           5      3
3         1    3           0   1600           1      9
4         1    2           1   1200           5      1

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 1)

In [20]:
print("X_train dataset", len(X_train))
print("y_train dataset",len(y_train))

X_train dataset 750
y_train dataset 750


In [21]:
print("X_test dataset", len(X_test))
print("y_test dataset",len(y_test))

X_test dataset 250
y_test dataset 250


In [22]:
reg = LinearRegression()

In [23]:
reg.fit(X_train,y_train)     #training the model

LinearRegression()

In [24]:
reg.coef_

array([4225.34712608, 2402.49034817,  984.95122323,    8.67968463,
        -55.68969279,  526.95532777])

In [25]:
reg.intercept_

459.03770000992154

In [26]:
X_test.head()

Location  BHK  Furnishing  Sq.ft  Old(years)  Floor
507         1    3           0   2180           1     11
818         1    3           0   2180           1     11
452         1    3           1   1760           5      8
368         1    3           0   3155           1      1
242         1    3           0   2200           1     10

In [27]:
y_test.head()

507    35000
818    35000
452    39500
368    45000
242    42000
Name: Price, dtype: int64

In [28]:
y_pred = reg.predict(X_test)

In [29]:
reg.predict([[1,3,0,3155,1,1]])

array([39747.5265149])

In [30]:
reg.predict([[1,3,0,2180,1,11]])

array([36554.38727788])

In [31]:
acc = (sum(y_pred)/sum(y_test))

In [32]:
print(acc)

1.0178835829517459


In [33]:
#accuracy_score(y_test,y_pred)